dhcp-authoritative

#The RFP host definiton, MAC, IP, HOSTNAME
dhcp-host=00:30:42:17:86:8b,10.10.10.10,eda1
dhcp-host=00:30:42:29:11:8c,10.10.10.11,eda2
dhcp-host=00:30:42:29:11:97,10.10.10.12,eda3
dhcp-host=00:30:42:29:11:ae,10.10.10.13,eda4
dhcp-host=00:30:42:25:53:a4,10.10.10.14,eda5

#The location of the leasefile
dhcp-leasefile=/var/lib/dnsmasq/dnsmasq.leases

#If a devices says in the dhcp discover packet, that it is from vendor OpenMobility* the dhcp server will set vendor specific options, which equals the code 43 from the dhcpd example, with the option code 10, and the IP adress.
#With out that the rfp will just ignore the dhcp offer and send another discover packet.
#The 10 says hey you are running the omm now and the ip points the rfp to the omm.
#If you want to run the om on an other device you have to change the 10 with a 19, just like in the other example above.
dhcp-option=vendor:OpenMobility,10,10.10.10.10

#Defines the range of IP-Adresses handed out by dnsmasq with the subnet mask and lease time
dhcp-range=10.10.10.100,10.10.10.199,255.255.255.0,6h

#Interface to listen on
interface=ens19

#Disables dnsmasq on dns server
port=53

#DNS Server to use
server=9.9.9.9
server=149.112.112.112
