[general]
static=yes
writeprotect=yes
clearglobalvars=no

;; --  Start of Configuration --

;; -- Context temp, ext, etc

[from_temp_dect]


; #finde_me token
; update if other tokensyntax is used
exten = _01990.,1,NoOp()
same = n,Answer()
same = n,Playback("selfservice_ansage")
same = n,Verbose("Temporäre Nummer ${CALLERID(num)} hat Token ${EXTEN} angerufen")
same = n,Set(save_CALLERID=${FILTER(A-Za-z0-9_\-, ${CALLERID(num)})})
same = n,Set(save_EXTEN=${FILTER(A-Za-z0-9_\-, ${EXTEN})})
same = n,Set(connect_api_stdout=${SHELL(curl -X POST -H "Content-Type: application/json" --data '{"callerid":"${save_CALLERID}","token":"${save_EXTEN}"}' http://127.0.0.1:8081/connect/)})
same = n,Verbose("Output for Connect/API/CURL ${connect_api_stdout}")

; goto error if something went wrong
; we can't play a sound for success - on success our sip-extenstion gets removed on the omm -> instant disconnect
same = n,GotoIf($[${REGEX("extension added" ${connect_api_stdout})}]?hangup:error)

same = n(error),Verbose("error")
same = n,Playback("selfservice_error")

same = n(hangup),Hangup()



include => utils
include => call_groups
include => call_extensions
include => call_temp_extensions

[from_user]

;exten = 862,1,NoOp()
;same = n,SET(DB(callstats/videohotline)=$[0${DB(callstats/videohotline)}+1])
;same = n,Dial(PJSIP/2003&PJSIP/725&PJSIP/5040)
;same = n,Hangup()

;exten = h,1,NoOp()
;same = n,SET(DB(callstats/anrufe)=$[0${DB(callstats/anrufe)}+1])
;same = n,Return()

exten = _01999.,1,NoOp()
same = n,Dial(PJSIP/${EXTEN:5}@epvpn)

include => utils
include => call_groups
include => call_extensions
include => call_temp_extensions

;same = n,SET(DB(callstats/duration/${ARG1})=$[0${DB(callstats/duration/${ARG1})}+${CDR(billsec)}])

;; -- EXTENSTIONS and Groups --

[call_extensions]
exten = _XX.,1,NoOp()
same = n,Dial(${PJSIP_DIAL_CONTACTS(${EXTEN})},120)
same = n,Hangup()

[call_temp_extensions]
exten = _t.,1,NoOp()
same = n,Dial(${PJSIP_DIAL_CONTACTS(${EXTEN})},120)
same = n,Hangup()

[call_groups]
exten = 2000,1,NoOp()
;same = n,Answer()
same = n,Dial(PJSIP/7590&PJSIP/4144,120)
same = n,Hangup()

;; -- Utils, Netzansagen, Stuff  ---
[utils]

exten = _031[0-1],1,NoOp()
same = n,Answer()
same = n,Verbose("${CALLERID(num)} Called Netzansage")
same = n,Playback("netzansage")
same = n,Hangup()


exten = 9999,1,NoOp()
same = n,Answer()
same = n,Echo()
same = n,Hangup()

;; -- DIALIN --

[dialin]
exten = _.,1,NoOp()
same = n,Goto(dialin-s1-extract-to-header,${EXTEN},1)


[dialin-s1-extract-to-header]
;; extract to-header and save it in to_header
;; now give call to s2

exten = _.,1,NoOp()
same = n,NoOp(Attempting to extract DID from SIP To header)
same = n,Set(to_header=${CUT(CUT(PJSIP_HEADER(read,To),@,1),:,2)})
same = n,Goto(dialin-s2-extract-ddi,${to_header},1)

[dialin-s2-extract-ddi]
;; extract ddi from to_header
;; now give call to distri

exten = _+49941383388.,1,NoOp()
same = n,Verbose("extracted DDI=${EXTEN:12}")
same = n,Goto(dialin-distri,${EXTEN:12},1)

[dialin-distri]

include => utils
include => call_groups
include => call_extensions

