;; --  Start of Configuration --

;;  user templates

[user](!)
type = wizard
transport = udp4
accepts_auth = yes
accepts_registrations = yes
endpoint/allow = !all,g722,alaw,ulaw,gsm
endpoint/direct_media = no
aor/max_contacts = 32
aor/remove_existing = no
aor/remove_unavailable = no
aor/qualify_frequency = 30
aor/qualify_timeout = 3.0
aor/minimum_expiration = 30
aor/maximum_expiration = 600
aor/authenticate_qualify = yes
endpoint/context = from_user
endpoint/force_rport = yes
endpoint/rewrite_contact = yes
endpoint/timers = yes
endpoint/timers_min_se = 90
endpoint/timers_sess_expires = 3600
endpoint/rtp_keepalive = 30
endpoint/rtp_timeout = 600
endpoint/rtp_timeout_hold = 3600

[temp_dect](!)
type = wizard
transport = udp4
accepts_auth = yes
accepts_registrations = yes
endpoint/allow = !all,g722,alaw,ulaw,gsm
endpoint/direct_media = no
aor/max_contacts = 1
aor/remove_existing = yes
endpoint/context = from_temp_dect

;; dialin templates

[dialin](!)
type = wizard
sends_auth = yes
sends_registrations = yes
transport = udp4
endpoint/allow = !all,g722,alaw,ulaw,gsm
endpoint/context = dialin
aor/qualify_frequency = 30
registration/expiration = 600

;; accounts

#include /etc/asterisk/pjsip_wizard_user.conf
#include /etc/asterisk/pjsip_wizard_temp.conf

;;[fonial](dialin)
;;remote_hosts = sip.plusnet.de:5060
;;outbound_auth/username = fluff
;;outbound_auth/password = 01189998819991197253

;;[epvpn](dialin)
;;remote_hosts = hg.eventphone.de
;;outbound_auth/username = 1337
;;outbound_auth/password = 01189998819991197253
